runtime: python27                                                                                                                                                 
api_version: 1
threadsafe: true

service: default

# scaling
automatic_scaling:
  min_idle_instances: 1
  # max_idle_instances: automatic  # default value
  max_idle_instances: 2 # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
# basic_scaling:
#   max_instances: 11
#   idle_timeout: 10m
# manual_scaling:
#   instances: 1


handlers:
- url: /.*
  script: main.app
